//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.Organisatons.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterOrganisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterOrganisation()
        {
            this.Org_HMPP_Postcode = new HashSet<Org_HMPP_Postcode>();
            this.Org_HMPP_UOP = new HashSet<Org_HMPP_UOP>();
            this.Org_PartnerUKPRN = new HashSet<Org_PartnerUKPRN>();
            this.Org_UKPRN_UPIN = new HashSet<Org_UKPRN_UPIN>();
            this.Org_Funding = new HashSet<Org_Funding>();
        }
    
        public long UKPRN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_HMPP_Postcode> Org_HMPP_Postcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_HMPP_UOP> Org_HMPP_UOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_PartnerUKPRN> Org_PartnerUKPRN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_UKPRN_UPIN> Org_UKPRN_UPIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_Funding> Org_Funding { get; set; }
        public virtual Org_Details Org_Details { get; set; }
    }
}
