//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.Organisatons.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_Funding
    {
        public long UKPRN { get; set; }
        public string FundModelName { get; set; }
        public string FundingFactor { get; set; }
        public string FundingFactorType { get; set; }
        public string FundingFactorValue { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public string CODACode { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual MasterOrganisation MasterOrganisation { get; set; }
    }
}
