//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.Organisatons.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_DataGeneration
    {
        public System.DateTime DataGeneratedOn { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
    }
}
