//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.Organisatons.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_Details
    {
        public long UKPRN { get; set; }
        public string Name { get; set; }
        public string OrganisationCode { get; set; }
        public string SubLocation { get; set; }
        public string Location { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string Locality { get; set; }
        public string Postcode { get; set; }
        public string ExternalData { get; set; }
        public string PhaseEduc { get; set; }
        public string GovOffReg { get; set; }
        public string LegalOrgType { get; set; }
        public string Status { get; set; }
        public string StatusExtended { get; set; }
        public Nullable<int> ThirdSector { get; set; }
        public Nullable<int> AccERGFold { get; set; }
        public Nullable<int> ContAppsTrainAgncy { get; set; }
        public Nullable<int> DanceDramaAward { get; set; }
        public Nullable<int> DirectFund { get; set; }
        public Nullable<int> EmpOnlyTrain { get; set; }
        public Nullable<int> IndepOrg { get; set; }
        public Nullable<int> IssueAuth { get; set; }
        public Nullable<int> LLDDIndepSpec { get; set; }
        public Nullable<int> NatSkillsAcademy { get; set; }
        public Nullable<int> PotThirdSector { get; set; }
        public Nullable<int> NASEmpUnit { get; set; }
        public Nullable<int> School6Form { get; set; }
        public Nullable<int> TertiaryColl { get; set; }
        public string OFSTEDEffect { get; set; }
        public string OFSTED_AchStnd { get; set; }
        public string DfEEstabNum { get; set; }
        public string EduBLocAuthSchEst { get; set; }
        public string EdubaseURN { get; set; }
        public string LEACode { get; set; }
        public string LocalAuthCode { get; set; }
        public Nullable<int> LongTermResid { get; set; }
        public Nullable<int> OfstedCareStds { get; set; }
        public string OFSTEDNonEduBURN { get; set; }
        public Nullable<int> SpecialResources { get; set; }
        public Nullable<int> StatryHighAge { get; set; }
        public Nullable<int> StatryLowAge { get; set; }
        public string OFSTEDRep { get; set; }
        public string OFSTEDInsp { get; set; }
        public Nullable<int> UKLearnProv { get; set; }
        public Nullable<int> AgencyTrainProv { get; set; }
        public Nullable<int> FundBody { get; set; }
        public Nullable<int> EducProv { get; set; }
        public Nullable<int> LocalAuthority { get; set; }
        public Nullable<int> RegCompany { get; set; }
        public Nullable<int> RegCharity { get; set; }
        public Nullable<int> Auditor { get; set; }
        public string AwardOrgCode { get; set; }
        public Nullable<int> SecSkillsCoun { get; set; }
        public Nullable<int> SectorLeadBody { get; set; }
        public Nullable<int> Regulator { get; set; }
        public Nullable<int> HMPP { get; set; }
        public Nullable<int> DanceAndDramaIndicator { get; set; }
        public Nullable<int> DirectFundedEmpIndicator { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> HESAProvider { get; set; }
    
        public virtual MasterOrganisation MasterOrganisation { get; set; }
    }
}
